# Generated by Django 4.2.28 on 2026-04-15 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_initial', models.CharField(max_length=1)),
                ('designation', models.CharField(max_length=150)),
                ('mobile_cp_no', models.CharField(max_length=30)),
                ('viber_no', models.CharField(max_length=30)),
                ('gcash_no', models.CharField(max_length=30)),
                ('personal_email_address', models.EmailField(max_length=254)),
                ('company_name', models.CharField(max_length=200)),
                ('industry_type', models.CharField(max_length=150)),
                ('company_office_address', models.TextField()),
                ('company_landline_no', models.CharField(max_length=30)),
                ('company_email_address', models.EmailField(max_length=254)),
                ('data_privacy_consent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
