# Generated by Django 6.0.4 on 2026-04-15 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='attendee_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='company_id_to_bring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='vehicle_type',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='will_come',
            field=models.BooleanField(default=True),
        ),
    ]
