# Generated by Django 4.2.28 on 2026-04-15 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0002_eventregistration_attendee_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregistration',
            name='middle_initial',
            field=models.CharField(max_length=2),
        ),
    ]
