# Generated by Django 4.2.28 on 2026-04-16 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0003_alter_eventregistration_middle_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='additional_attendees',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
