# Generated by Django 4.2.28 on 2026-04-16 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0004_eventregistration_additional_attendees'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='company_category',
            field=models.CharField(default='private', max_length=20),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='facebook_account',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='linkedin_account',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='messenger_account',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
