# Generated by Django 4.2.28 on 2026-04-20 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0005_eventregistration_social_accounts_and_company_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_satisfaction', models.PositiveSmallIntegerField()),
                ('job_relevance', models.PositiveSmallIntegerField()),
                ('key_takeaways', models.TextField(blank=True, default='')),
                ('logistics_ratings', models.JSONField(default=dict)),
                ('logistics_feedback', models.TextField()),
                ('session_relevance', models.JSONField(default=dict)),
                ('session_comments', models.TextField(blank=True, default='')),
                ('overall_feedback', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
