# Generated by Django 4.2.28 on 2026-04-20 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0006_eventfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventfeedback',
            name='personal_company_info_consent',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
